### PR TITLE
[NVIDIA TF] Optimize embedding_lookup_sparse using new grad op [PART 3/3]

### PR DESCRIPTION
**Pull request by benbarsdell**
See https://github.com/tensorflow/tensorflow/pull/60383 and https://github.com/benbarsdell/tensorflow/pull/1

(Note that this is currently targeting the Part 2 branch for ease of reviewing).

cc @nluehr @pjannaty

### CODE REVIEW

**Review by bfontain — APPROVED** [review]
LGTM, thanks for this improvement!

**Comment by bfontain** [comment]
One quick question, do you know if `tf.nn.safe_embedding_lookup_sparse` has the same issue?

**Comment by benbarsdell** [comment]
Thanks for the review.
`tf.nn.safe_embedding_lookup_sparse` calls `tf.nn.embedding_lookup_sparse` internally:
https://github.com/tensorflow/tensorflow/blob/v2.12.0/tensorflow/python/ops/embedding_ops.py#L921

**Comment by benbarsdell** [comment]
Moving this PR to https://github.com/tensorflow/tensorflow/pull/61491

**Pull request closed without merging**
